package runtime

// Committed pnpm lock fixtures for the Node engine tests. They are embedded
// (rather than resolved at test time) so the tests are deterministic and prove
// that `pnpm install --prod --frozen-lockfile` never re-resolves: pnpm must
// accept these locks as-is. They were generated by the pinned pnpm
// (runtime.PnpmImageTag) for the exact package.json shapes the tests use.
//
// These fixtures live in a build-tag-free file so both the unit tests and the
// integration tests (compiled only with -tags=integration) can share them.

// nodePnpmLockEmpty is the lock for {"type":"module"} with no dependencies.
const nodePnpmLockEmpty = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .: {}
`

// nodePnpmLockPicocolors is the lock for
// {"dependencies":{"picocolors":"^1.0.0"}}.
const nodePnpmLockPicocolors = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      picocolors:
        specifier: ^1.0.0
        version: 1.1.1

packages:

  picocolors@1.1.1:
    resolution: {integrity: sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==}

snapshots:

  picocolors@1.1.1: {}
`

// nodePnpmLockPicocolorsMs is the lock for
// {"dependencies":{"picocolors":"^1.0.0","ms":"2.1.3"}}.
const nodePnpmLockPicocolorsMs = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      ms:
        specifier: 2.1.3
        version: 2.1.3
      picocolors:
        specifier: ^1.0.0
        version: 1.1.1

packages:

  ms@2.1.3:
    resolution: {integrity: sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==}

  picocolors@1.1.1:
    resolution: {integrity: sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==}

snapshots:

  ms@2.1.3: {}

  picocolors@1.1.1: {}
`
